### ISSUE TITLE
Punto esclarrogativo - Parola che effettivamente esiste

### ISSUE THREAD

**Issue by RubenVerg** [GioRolf/PowerPizzonario#1]
According to Wikipedia, "punto esclarrogativo" è il nome corretto italiano per ‽

Vale comunque per essere inserita nel the_zionario?

**Comment by GioRolf** [comment]
Ciao!
Grazie mille per la domanda! 
Nonostante sia una parola vera, la lasciamo dentro perchè, fondamentalmente, è una Nickata. Considerando che pensava fosse una parola inventata... 

Grazie ancora per aver scritto!

**Comment by RubenVerg** [comment]
Effettivamente potevano inventarsi una traduzione piú decente…
